### ISSUE TITLE
`get_landsat_pairs_for_reference_scene()` fails with TypeError

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/its-live-monitoring#146] opened 2024-08-20 21:28 UTC
For a small subset of landsat scenes, `landsat.get_landsat_pairs_for_reference_scene` fails with `TypeError: ufunc 'create_collection' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`:

```
>>> item = landsat.get_landsat_stac_item('LC08_L1GT_012122_20221018_20221031_02_T2')
>>> pairs = landsat.get_landsat_pairs_for_reference_scene(item)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/its-live-monitoring/its_live_monitoring/src/landsat.py", line 125, in get_landsat_pairs_for_reference_scene
    df = gpd.GeoDataFrame.from_features(features)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/miniforge3/envs/its-live-monitoring/lib/python3.12/site-packages/geopandas/geodataframe.py", line 737, in from_features
    "geometry": shape(feature["geometry"]) if feature["geometry"] else None
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/miniforge3/envs/its-live-monitoring/lib/python3.12/site-packages/shapely/geometry/geo.py", line 107, in shape
    return MultiPolygon([[c[0], c[1:]] for c in ob["coordinates"]])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/miniforge3/envs/its-live-monitoring/lib/python3.12/site-packages/shapely/geometry/multipolygon.py", line 89, in __new__
    return shapely.multipolygons(subs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/miniforge3/envs/its-live-monitoring/lib/python3.12/site-packages/shapely/decorators.py", line 77, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/miniforge3/envs/its-live-monitoring/lib/python3.12/site-packages/shapely/creation.py", line 429, in multipolygons
    return lib.create_collection(geometries, typ, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ufunc 'create_collection' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Handful of other examples:
```
LC08_L1GT_012122_20220220_20220302_02_T2
LC09_L1GT_012122_20220212_20230427_02_T2
LC08_L1GT_012122_20221018_20221031_02_T2
LC09_L1GT_012122_20221229_20230315_02_T2
LC08_L1GT_012122_20220119_20220127_02_T2
LC09_L1GT_012122_20220111_20230502_02_T2
LC08_L1GT_012122_20221205_20230112_02_T2
```

**Comment by jhkennedy** [comment] 2024-11-22 03:40
:thinking: I'm not able to reproduce this issue with any of the scenes listed in this issue, so I suspect it's been fixed upstream. I will close this, but if you see it again, please re-open it!

**Closed by jhkennedy** 2024-11-22 03:40 UTC
